Clase-6/Clase6.PasajeDeDatos/Clase6.PasajeDeDatos.Web/Models/EstadioViewModel.cs
namespace Clase6.PasajeDeDatos.Web.Models
{
    public class EstadioViewModel
    {
        public int Id { get; set; }
        public string? Nombre { get; set; }
        public string? urlImagenEstadio{ get; set; }
       
        public SeleccionViewModel? SeleccionPerteneciente { get; set; }
    }
}

Clase-6/Clase6.PasajeDeDatos/Clase6.PasajeDeDatos.Web/Models/SeleccionViewModel.cs
namespace Clase6.PasajeDeDatos.Web.Models
{
    public class SeleccionViewModel
    {
        public int Id { get; set; }
        public string? Nombre { get; set; }
        public string? Apodo { get; set; }
    }
}

Clase-6/Clase6.PasajeDeDatos/Clase6.PasajeDeDatos.Web/Controllers/ColoresController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Drawing;
using System.Text;

namespace Clase6.PasajeDeDatos.Web.Controllers
{
    public class ColoresController : Controller
    {
        public IActionResult Index()
        {
            List<string> colores = new List<string> { "red", "green", "blue", "yellow", "purple" };
            return View(colores);
        }
        [HttpPost]
        public IActionResult CambiarColorFondo(string color) {
            if (!string.IsNullOrEmpty(color))
            {
                HttpContext.Session.SetString("ColorFondo",color);
            }
            return RedirectToAction("Index");
        }
    }
}

Clase-6/Clase6.PasajeDeDatos/Clase6.PasajeDeDatos.Web/Controllers/EstadiosController.cs
using Clase6.PasajeDeDatos.Web.Models;
using Microsoft.AspNetCore.Mvc;

namespace Clase6.PasajeDeDatos.Web.Controllers
{
    public class EstadiosController : Controller
    {
        public IActionResult Index()
        {
            var estadioSudamericanos = new List<EstadioViewModel>()
            {
                new EstadioViewModel()
                {
                    Id = 1,
                    Nombre = "Mâs Monumental",
                    urlImagenEstadio = "https://upload.wikimedia.org/wikipedia/commons/thumb/5/54/RiverPlateStadium.jpg/273px-RiverPlateStadium.jpg",
                    SeleccionPerteneciente = new SeleccionViewModel()
                    {
                        Id = 1,
                        Nombre = "Argentina"
                    }
    },
                new EstadioViewModel()
                {
                    Id = 2,
                    Nombre = "Monumental U Marathon",
                    urlImagenEstadio = "https://upload.wikimedia.org/wikipedia/commons/c/c4/Estadio_Monumental_2021.jpg",
                 SeleccionPerteneciente = new SeleccionViewModel()
                
                },
                new EstadioViewModel()
                {
                    Id = 3,
                    Nombre = "Maracaná",
                    urlImagenEstadio = "https://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Vis%C3%A3o_do_torcedor.JPG/800px-Vis%C3%A3o_do_torcedor.JPG",
                  SeleccionPerteneciente = new SeleccionViewModel()
                },
            
    
            };

            return View(estadioSudamericanos);
        }
    }
}

Clase-6/Clase6.PasajeDeDatos/Clase6.PasajeDeDatos.Web/Controllers/HomeController.cs
using System.Diagnostics;
using Clase6.PasajeDeDatos.Web.Models;
using Microsoft.AspNetCore.Mvc;

namespace Clase6.PasajeDeDatos.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }
    }
}

Clase-6/Clase6.PasajeDeDatos/Clase6.PasajeDeDatos.Web/Controllers/JugadoresController.cs
using Microsoft.AspNetCore.Mvc;

namespace Clase6.PasajeDeDatos.Web.Controllers
{
    public class Jugador
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Apellido { get; set; }
    }
    public class JugadoresController : Controller
    {
        public IActionResult Index()
        {
            List<string> competencias = new List<string>();
            competencias.Add("Copa America Brasil 2021");
            competencias.Add("Mundial Qatar 2022");
            ViewBag.Competencias = competencias;

            List<Jugador> jugadores = new List<Jugador>();
            jugadores.Add(new Jugador()
            {
                Id = 1,
                Nombre = "Julian",
                Apellido = "Alvarez"
            });

            jugadores.Add(new Jugador()
            {
                Id = 2,
                Nombre = "Leandro",
                Apellido = "Paredes"
            });

            ViewBag.Jugadores = jugadores;
            return View();
        }

        public IActionResult CalcularPromedioDeGol()
        {
            return View();
        }

        [HttpPost]
        public IActionResult CalcularPromedioDeGol(double partidos, double goles)
        {
            ViewBag.Partidos = partidos;
            ViewBag.Goles = goles;
            ViewBag.PromedioDeGol = goles / partidos;
            return View();
        }

        public IActionResult IngresarUltimoTweetDeJugador()
        {
            return View();
        }


       

        public IActionResult UltimoJugador(string UltimoJugador)
        {//Me di cuenta que en esta instancia no puedo agregar el nuevo jugador
         //a la array creado en el action index
            TempData["UltimoJugador"]=UltimoJugador;

            return RedirectToAction("Index","home");
        }
        [HttpPost]
        public IActionResult IngresarUltimoTweetDeJugador(string usuarioTwiter, string tweet)
        {
            TempData["UsuarioTwiter"] = usuarioTwiter;
            TempData["Tweet"] = tweet;
            return RedirectToAction("Index");
        }
    }
}

Clase-6/Clase6.PasajeDeDatos/Clase6.PasajeDeDatos.Web/Controllers/SeleccionesController.cs
using Clase6.PasajeDeDatos.Web.Models;
using Microsoft.AspNetCore.Mvc;

namespace Clase6.PasajeDeDatos.Web.Controllers
{
    public class SeleccionesController : Controller
    {
        public IActionResult Index()
        {
            var seleccionesSudamericanasEliminatorias2026 = new List<SeleccionViewModel>()
            {
                new SeleccionViewModel()
                {
                    Id = 1,
                    Nombre = "Argentina",
                    Apodo = "La Albiceleste"
                },
                new SeleccionViewModel()
                {
                    Id = 2,
                    Nombre = "Bolivia",
                    Apodo = "La Verde"
                },
                new SeleccionViewModel()
                {
                    Id = 3,
                    Nombre = "Brasil",
                    Apodo = "La Verdeamarela"
                },
                new SeleccionViewModel()
                {
                    Id = 4,
                    Nombre = "Chile",
                    Apodo = "La Roja"
                },
                new SeleccionViewModel()
                {
                    Id = 5,
                    Nombre = "Colombia",
                    Apodo = "Los Cafeteros"
                },
                new SeleccionViewModel()
                {
                    Id = 6,
                    Nombre = "Ecuador",
                    Apodo = "La Tri"
                },
                new SeleccionViewModel()
                {
                    Id = 7,
                    Nombre = "Paraguay",
                    Apodo = "La Albirroja"
                },
                new SeleccionViewModel()
                {
                    Id = 8,
                    Nombre = "Peru",
                    Apodo = "La Blanquirroja"
                },
                new SeleccionViewModel()
                {
                    Id = 9,
                    Nombre = "Uruguay",
                    Apodo = "La Celeste"
                },
                new SeleccionViewModel()
                {
                    Id = 10,
                    Nombre = "Venezuela",
                    Apodo = "La Vinotinto"
                }
            };
            return View(seleccionesSudamericanasEliminatorias2026);
        }

        [HttpPost]
        public IActionResult Index(IFormCollection form)
        {
            string nombreBoton = form.Keys.FirstOrDefault(k => !string.IsNullOrEmpty(form[k]));
            if (!string.IsNullOrEmpty(nombreBoton))
                HttpContext.Session.SetString("SeleccionFavorita", nombreBoton);
            return RedirectToAction("Index");
        }
    }
}

Clase-6/Clase6.PasajeDeDatos/Clase6.PasajeDeDatos.Web/Views/Estadios/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model List<EstadioViewModel>
<div>
    <h2>ESTADIOS SUDAMERICANOS</h2>
    <ul>
        @foreach (EstadioViewModel estadio in Model)
        {
            <li>@estadio.Nombre (*)</li>
            <h5>@estadio.SeleccionPerteneciente.Nombre</h5>
            @if (@estadio.SeleccionPerteneciente.Nombre == null)
            {
                <h5>
                    Pais Perteneciente no ingresado</h5>
               
            }
            <img src=@estadio.urlImagenEstadio width="300">
        }
    </ul>
</div>
<div>
    <a href="https://es.wikipedia.org/wiki/Anexo:Estadios_de_f%C3%BAtbol_de_Am%C3%A9rica_del_Sur">Mas informacion en Wiki...</a>
    
</div>

Clase-6/Clase6.PasajeDeDatos/Clase6.PasajeDeDatos.Web/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http
@inject IHttpContextAccessor HttpContextAccessor

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Clase6.PasajeDeDatos.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Clase6.PasajeDeDatos.Web.styles.css" asp-append-version="true" />
    <style>
        body {
            background-color: @(ViewContext.HttpContext.Session.GetString("ColorFondo") ?? "white");
        }
    </style>
</head>
<body >
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Clase6.PasajeDeDatos.Web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Jugadores" asp-action="Index">ViewBag - Jugadores</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Selecciones" asp-action="Index">ViewModel - Selecciones</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Jugadores" asp-action="CalcularPromedioDeGol">Calcular Promedio DeGol</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Colores" asp-action="Index">Colores-session</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Estadios" asp-action="Index">Estadios-Viewmodel</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <!--renderizo la imagen de la bandera de la seleccion elegida de sudamerica -->
            @{
                string seleccionFavorita = HttpContextAccessor.HttpContext.Session.GetString("SeleccionFavorita");
                if (seleccionFavorita != null)
                {
                    <img height="60" width="100" src="@Html.Raw("https://norfipc.com/img/banderas/bandera-" + seleccionFavorita.ToLower() + ".png")" />
                }
            }
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Clase6.PasajeDeDatos.Web
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>