Clase-3/Clase3.MVC/Clase3.MVC.Web/Models/ClassViewModel.cs
using Clase3.MVC.Dominio.Entidades;

namespace Clase3.MVC.Web.Models
{
    public class ClassViewModel
    {
        public Poder poder { get; set; }
        public List<TipoPoder> tipoPoder { get; set; }

        public List<Poder> poderes { get; set; }
    }
}

Clase-3/Clase3.MVC/Clase3.MVC.Web/Models/ErrorViewModel.cs
namespace Clase3.MVC.Web.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Clase-3/Clase3.MVC/Clase3.MVC.Web/Models/PoderViewModel.cs
using Clase3.MVC.Dominio.Entidades;

namespace Clase3.MVC.Web.Models
{
    public class PoderViewModel
    {
        public int Id { get; set; }
        public string Nombre { get; set; }
        public TipoPoder Tipo { get; set; }
        public int Daño { get; set; }
        public List<TipoPoder> Tipos { get; set; }
    }
}

Clase-3/Clase3.MVC/Clase3.MVC.Web/Controllers/HomeController.cs
using System.Diagnostics;
using Clase3.MVC.Web.Models;
using Microsoft.AspNetCore.Mvc;

namespace Clase3.MVC.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }
    }
}

Clase-3/Clase3.MVC/Clase3.MVC.Web/Controllers/PoderesController.cs
using Clase3.MVC.Dominio.Entidades;
using Clase3.MVC.Dominio.Logica;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Clase3.MVC.Web.Controllers
{
    public class PoderesController : Controller
    {
        IPoderesRepositorio _poderRepositorio;
        ITipoPoderRepositorio _tipoPoderesR;
        public PoderesController(IPoderesRepositorio poderesRepositorio, ITipoPoderRepositorio tipoPoderesRepositori) {
            _poderRepositorio = poderesRepositorio;
            _tipoPoderesR = tipoPoderesRepositori;
        }

        // GET: PoderesController
        public IActionResult Index()
        {
            var poderes = _poderRepositorio.ObtenerTodos();
            return View(poderes);
        }

        [HttpGet]
        public ActionResult Agregar()
        {
            var tipos = _tipoPoderesR.ObtenerTodos();
            ViewBag.Tipos = new SelectList(tipos, "Id", "Nombre");
            return View();
        }

        [HttpPost]
        public IActionResult Agregar(Poder poderes)
        {
            try
            {
                var tipos = _tipoPoderesR.ObtenerTodos();
                TipoPoder? tipoPoder = tipos.FirstOrDefault(t => t.Id == poderes.Tipo.Id);
                poderes.Tipo = tipoPoder;
                //System.Diagnostics.Debug.WriteLine("El valor de la variable es: " + ViewBag.Tipos);
                _poderRepositorio.Agregar(poderes);
            }
            catch (ArgumentException ex)
            {
                ViewBag.Mensaje = $"El nombre de poder {poderes.Nombre} ya existe";
                return View(poderes);
            }
            catch (Exception ex)
            {
                ViewBag.Mensaje = ex.Message;
                return View(poderes);
            }

            return RedirectToAction("Index");
        }

        // GET: PoderesController/Details/5
        public ActionResult Detalles(int id)
        {

            var poder = _poderRepositorio.buscarPorID(id);
            return View(poder);
        }

   
        public ActionResult eliminar(int id)
        {
            _poderRepositorio.Eliminar(id);
            return RedirectToAction("Index");
        }

        // GET: PoderesController/modificar/5
        public ActionResult modificar(int id) {

            var poder = _poderRepositorio.buscarPorID(id);
            var tipos = _tipoPoderesR.ObtenerTodos();
            ViewBag.Tipos = new SelectList(tipos, "Id", "Nombre");
            return View(poder);

        }

        // Post/¿Put?: PoderesController/modificar
        [HttpPost]
        public IActionResult modificar(Poder poderes)
        {
            try
            {
                var tipos = _tipoPoderesR.ObtenerTodos();
                TipoPoder? tipoPoder = tipos.FirstOrDefault(t => t.Id == poderes.Tipo.Id);
                poderes.Tipo = tipoPoder;
                //System.Diagnostics.Debug.WriteLine("El valor de la variable es: " + ViewBag.Tipos);
                _poderRepositorio.modificar(poderes);
            }
            catch (ArgumentException ex)
            {
                ViewBag.Mensaje = $"El nombre de poder {poderes.Nombre} ya existe";
                return View(poderes);
            }
            catch (Exception ex)
            {
                ViewBag.Mensaje = ex.Message;
                return View(poderes);
            }

            return RedirectToAction("Index");
        }

    }

        
}

Clase-3/Clase3.MVC/Clase3.MVC.Web/Controllers/TipoPoderesController.cs
using Clase3.MVC.Dominio.Entidades;
using Clase3.MVC.Dominio.Logica;
using Microsoft.AspNetCore.Mvc;

namespace Clase3.MVC.Web.Controllers
{
    public class TipoPoderesController : Controller
    {
        ITipoPoderRepositorio _tipoPoderRepositorio;
        public TipoPoderesController(ITipoPoderRepositorio tipoPoderRepositorio)
        {
            _tipoPoderRepositorio = tipoPoderRepositorio;
        }
        public IActionResult Index()
        {
            var tiposPoderes = _tipoPoderRepositorio.ObtenerTodos();
            return View(tiposPoderes);
        }

        [HttpGet]
        public IActionResult Agregar()
        {
            var tipoPoder = _tipoPoderRepositorio.ObtenerTodos();
            return View();
        }

        [HttpGet]
        public IActionResult Ver()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Detalle(int id)
        {
            var tipoPoder =  _tipoPoderRepositorio.ObtenerEspecifico(id);
            return View(tipoPoder);
        }

        [HttpPost]
        public IActionResult Agregar(TipoPoder tipoPoder)
        {
            try
            {
                _tipoPoderRepositorio.Agregar(tipoPoder);
            }
            catch (ArgumentException ex)
            {
               ViewBag.Mensaje = $"El nombre de poder {tipoPoder.Nombre} ya existe";
               return View(tipoPoder);
            }
            catch (Exception ex)
            {
                ViewBag.Mensaje = ex.Message;
                return View(tipoPoder);
            }

            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Eliminar(int id)
        {
            _tipoPoderRepositorio.Eliminar(id);
            return RedirectToAction("Index");
        }
    }
}

Clase-3/Clase3.MVC/Clase3.MVC.Web/Views/Poder/Agregar.cshtml
@model Clase3.MVC.Dominio.Entidades.Poder
<h1>Agregar Poder</h1>

@using (Html.BeginForm("Agregar", "Poder", FormMethod.Post))
{
<div>
    @Html.LabelFor(model => model.Nombre)
    @Html.TextBoxFor(model => model.Nombre)
    @Html.DropDownListFor(model => model.Tipo, new SelectList(Model.Tipo.Nombre, "Value", "Text"))
</div>
@if (!string.IsNullOrEmpty(ViewBag.Mensaje))
    {
<div class="alert alert-danger">
    @ViewBag.Mensaje
</div>
    }
<div>
    <input type="submit" value="Agregar" />
</div>
}

Clase-3/Clase3.MVC/Clase3.MVC.Web/Views/Poder/Detalle.cshtml
@model Clase3.MVC.Dominio.Entidades.Poder
@{
    ViewData["Title"] = "Detalle";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@{
}

<h1>Detalle</h1>
<h3>@Model.Nombre</h3>

Clase-3/Clase3.MVC/Clase3.MVC.Web/Views/Poder/EditarPoder.cshtml
@model Clase3.MVC.Dominio.Entidades.Poder

<h1>Editar Tipo de Poder</h1>
@using (Html.BeginForm("EditarPoder", "Poder", FormMethod.Post))
{
    @Html.HiddenFor(model => model.Id)
    <div>
        @Html.LabelFor(model => model.Nombre)
        @Html.TextBoxFor(model => model.Nombre)
    </div>
    @if (!string.IsNullOrEmpty(ViewBag.Mensaje))
    {
        <div class="alert alert-danger">
            @ViewBag.Mensaje
        </div>
    }
    <div>
        <input type="submit" value="Editar" />
    </div>
}

Clase-3/Clase3.MVC/Clase3.MVC.Web/Views/Poder/FormularioEditarPoder.cshtml
@model Clase3.MVC.Dominio.Entidades.Poder

<h1>Editar </h1>
@using (Html.BeginForm("EditarPoder", "Poder", FormMethod.Post))
{
    @Html.HiddenFor(model => model.Id)
    <div>
        @Html.LabelFor(model => model.Nombre)
        @Html.TextBoxFor(model => model.Nombre)
    </div>
    @if (string.IsNullOrEmpty(ViewBag.Mensaje))
    {
        <div class="alert alert-danger">
            @ViewBag.Mensaje
        </div>
    }
    <div>
        <input type="submit" value="Editar" />
    </div>
}

Clase-3/Clase3.MVC/Clase3.MVC.Web/Views/Poder/Index.cshtml
@model List<Clase3.MVC.Dominio.Entidades.Poder>
@{
    ViewBag.Title = "Poderes";
}
<a href="/poder/Agregar">Agregar Poder</a>
<table>
    <tr>
        <th>
            Id
        </th>
        <th>
            Nombre
        </th>
        <th>
            Accion
        </th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nombre)
            </td>
            <td>
                @Html.ActionLink("Ver", "Detalle", "Poder", new { id=item.Id }) |
                @Html.ActionLink("Eliminar", "Eliminar", "Poder", new { id=item.Id }) |
                @Html.ActionLink("Editar", "FormularioEditarPoder", "Poder", new { id=item.Id })
            </td>
        </tr>
    }
</table>

Clase-3/Clase3.MVC/Clase3.MVC.Web/Views/Poderes/Agregar.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model Clase3.MVC.Dominio.Entidades.Poder
<h1>Agregar Poder</h1>

@using (Html.BeginForm("Agregar", "Poderes", FormMethod.Post))
{
    <div>
        @Html.LabelFor(model => model.Nombre)
        @Html.TextBoxFor(model => model.Nombre)
        @Html.LabelFor(model => model.Tipo)
        @Html.DropDownListFor(model => model.Tipo.Id, ViewBag.Tipos as SelectList, "-- Seleccione un tipo --")
        @Html.LabelFor(model => model.Daño  )
        @Html.TextBoxFor(model => model.Daño)
    </div>
    @if (!string.IsNullOrEmpty(ViewBag.Mensaje))
    {
        <div class="alert alert-danger">
            @ViewBag.Mensaje
        </div>
    }
    <div>
        <input type="submit" value="Agregar" />
    </div>
}

Clase-3/Clase3.MVC/Clase3.MVC.Web/Views/Poderes/Detalle.cshtml
@model Clase3.MVC.Web.Models.ClassViewModel;
@{
    ViewBag.Title = "Poderes";
}
<table>
    <tr>
        <th>
            Id
        </th>
        <th>
            Nombre
        </th>
        <th>
            Tipo
        </th>
        <th>
            Daño
        </th>
    </tr>
    <tr>
        <td>
            @Html.DisplayFor(model => model.poder.Id)
        </td>
        <td>
            @Html.DisplayFor(model => model.poder.Nombre)
        </td>
        <td>
            @Html.DisplayFor(model => model.poder.Tipo.Nombre)
        </td>
        <td>
            @Html.DisplayFor(model => model.poder.Daño)
        </td>
        <td>
            @Html.ActionLink("Eliminar", "Eliminar", "Poderes", new { id= Model.poder.Id})
            <a href="/poderes/index">Volver</a>
        </td>
    </tr>
</table>

Clase-3/Clase3.MVC/Clase3.MVC.Web/Views/Poderes/Index.cshtml
@model List<Clase3.MVC.Dominio.Entidades.Poder>
@{
    ViewBag.Title = "Poderes";
}
<a href="/poderes/Agregar">Agregar un Poder Nuevo</a>
<table>
<tr>
    <th>
        Id
    </th>
    <th>
        Nombre
    </th>
    <th>
        Accion
    </th>
</tr>

@foreach (var item in Model)
{
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Id)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Nombre)
        </td>
        <td>
            @Html.ActionLink("ver", "detalles", "poderes", new { id=item.Id }) |
            @Html.ActionLink("eliminar", "eliminar", "poderes", new { id=item.Id })|
            @Html.ActionLink("modificar", "modificar", "poderes", new { id=item.Id })
        </td>
    </tr>
}
</table>

Clase-3/Clase3.MVC/Clase3.MVC.Web/Views/Poderes/detalles.cshtml
@model Clase3.MVC.Dominio.Entidades.Poder
@{
    ViewBag.Title = "Detalles de Poderes";
}
<table>
    <tr>
        <th>
            Id
        </th>
        <th>
            Nombre
        </th>
        <th>
          ID_Tipo
        </th>
        <th>
            Tipo
        </th>
        <th>
           Daño
        </th>
    </tr>

  
        <tr>
            <td>
            @Html.DisplayFor(model => model.Id)
            </td>
            <td>
            @Html.DisplayFor(model => model.Nombre)
            </td>
            <td>
            @Html.DisplayFor(model => model.Tipo.Id)
            </td>
            <td>
            @Html.DisplayFor(model => model.Tipo.Nombre)
            </td>
            <td>
            @Html.DisplayFor(model => model.Daño)
            </td>
        </tr>

</table>

Clase-3/Clase3.MVC/Clase3.MVC.Web/Views/Poderes/modificar.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model Clase3.MVC.Dominio.Entidades.Poder
<h1>Modificar los Datos de Poder</h1>

@using (Html.BeginForm("Modificar", "Poderes", FormMethod.Post))
{
    <div>
        @Html.LabelFor(model => model.Nombre)
        @Html.TextBoxFor(model => model.Nombre)
        @Html.LabelFor(model => model.Tipo)
        @Html.DropDownListFor(model => model.Tipo.Id, ViewBag.Tipos as SelectList, "-- Seleccione un tipo --")
        @Html.LabelFor(model => model.Daño  )
        @Html.TextBoxFor(model => model.Daño)
    </div>
    @if (!string.IsNullOrEmpty(ViewBag.Mensaje))
    {
        <div class="alert alert-danger">
            @ViewBag.Mensaje
        </div>
    }

    <div>
        <input type="submit" value="Modificar" />
    </div>
}

Clase-3/Clase3.MVC/Clase3.MVC.Web/Views/TipoPoderes/Agregar.cshtml
@model Clase3.MVC.Dominio.Entidades.TipoPoder
<h1>Agregar Tipo Poder</h1>

@using (Html.BeginForm("Agregar", "TipoPoderes", FormMethod.Post))
{
    <div>
        @Html.LabelFor(model => model.Nombre)
        @Html.TextBoxFor(model => model.Nombre)
    </div>
    @if (!string.IsNullOrEmpty(ViewBag.Mensaje))
    {
        <div class="alert alert-danger">
            @ViewBag.Mensaje
        </div>
    }
    <div>
        <input type="submit" value="Agregar" />
    </div>
}

Clase-3/Clase3.MVC/Clase3.MVC.Web/Views/TipoPoderes/Detalle.cshtml
@model Clase3.MVC.Dominio.Entidades.TipoPoder
@{
    ViewBag.Title = "Tipo de Poder";
}
<table>
    <tr>
        <th>
            Id
        </th>
        <th>
            Nombre
        </th>
        <th>
            Accion
        </th>
    </tr>
    <tr>
        <td>
            @Html.DisplayFor(model => model.Id)
        </td>
        <td>
            @Html.DisplayFor(model => model.Nombre)
        </td>
        <td>
            <a href="/tipopoderes/index">Volver</a>
            @Html.ActionLink("Eliminar", "Eliminar", "TipoPoderes", new { id= Model.Id})
        </td>
    </tr>
</table>

Clase-3/Clase3.MVC/Clase3.MVC.Web/Views/TipoPoderes/EditarTipoPoder.cshtml
@model Clase3.MVC.Dominio.Entidades.TipoPoder

<h1>Editar Tipo de Poder</h1>
@using (Html.BeginForm("EditarTipoPoder", "TipoPoderes", FormMethod.Post))
{
    @Html.HiddenFor(model => model.Id)
    <div>
        @Html.LabelFor(model => model.Nombre)
        @Html.TextBoxFor(model => model.Nombre)
    </div>
    @if (!string.IsNullOrEmpty(ViewBag.Mensaje))
    {
        <div class="alert alert-danger">
            @ViewBag.Mensaje
        </div>
    }
    <div>
        <input type="submit" value="Editar" />
    </div>
}

Clase-3/Clase3.MVC/Clase3.MVC.Web/Views/TipoPoderes/FormularioEditarTipoPoder.cshtml
@model Clase3.MVC.Dominio.Entidades.TipoPoder

<h1>Editar </h1>
@using (Html.BeginForm("EditarTipoPoder", "TipoPoderes", FormMethod.Post))
{
    @Html.HiddenFor(model => model.Id)
    <div>
        @Html.LabelFor(model => model.Nombre)
        @Html.TextBoxFor(model => model.Nombre)
    </div>
    @if (string.IsNullOrEmpty(ViewBag.Mensaje))
    {
        <div class="alert alert-danger">
            @ViewBag.Mensaje
        </div>
    }
    <div>
        <input type="submit" value="Editare" />
    </div>
}

Clase-3/Clase3.MVC/Clase3.MVC.Web/Views/TipoPoderes/Index.cshtml
@model List<Clase3.MVC.Dominio.Entidades.TipoPoder>
@{
    ViewBag.Title = "Tipo de Poderes";
}
<a href="/TipoPoderes/Agregar">Agregar Tipo de Poder</a>
<table>
    <tr>
        <th>
            Id
        </th>
        <th>
            Nombre
        </th>
        <th>
            Accion
        </th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nombre)
            </td>
            <td>
                @Html.ActionLink("Ver", "Detalle", "TipoPoderes", new { id=item.Id }) |
                @Html.ActionLink("Eliminar", "Eliminar", "TipoPoderes", new { id=item.Id })
            </td>
        </tr>
    }
</table>