Clase-7/Clase7.EF.IslaDelTesoro/Clase7.EF.IslaDelTesoro.Web/Models/ErrorViewModel.cs
namespace Clase7.EF.IslaDelTesoro.Web.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Clase-7/Clase7.EF.IslaDelTesoro/Clase7.EF.IslaDelTesoro.Web/Controllers/CategoriasTesorosController.cs
using Clase7.EF.IslaDelTesoro.Logica;
using Microsoft.AspNetCore.Mvc;

namespace Clase7.EF.IslaDelTesoro.Web.Controllers
{
    public class CategoriasTesorosController : Controller
    {
        private ICategoriaTesoroServicio _categoriaTesoroServicio;
        public CategoriasTesorosController(ICategoriaTesoroServicio categoriaTesoroServicio)
        {
            _categoriaTesoroServicio = categoriaTesoroServicio;
        }
        public IActionResult Index()
        {
            return View(_categoriaTesoroServicio.ObtenerTodos());
        }

        public IActionResult Eliminar(int id)
        {
            _categoriaTesoroServicio.Eliminar(id);
            return RedirectToAction("Index");
        }
    }
}

Clase-7/Clase7.EF.IslaDelTesoro/Clase7.EF.IslaDelTesoro.Web/Controllers/HomeController.cs
using System.Diagnostics;
using Clase7.EF.IslaDelTesoro.Web.Models;
using Microsoft.AspNetCore.Mvc;

namespace Clase7.EF.IslaDelTesoro.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

    }
}

Clase-7/Clase7.EF.IslaDelTesoro/Clase7.EF.IslaDelTesoro.Web/Controllers/TesorosController.cs
using Clase7.EF.IslaDelTesoro.Data.Entidades;
using Clase7.EF.IslaDelTesoro.Logica;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Clase7.EF.IslaDelTesoro.Web.Controllers
{
    public class TesorosController : Controller
    {
        private PW320231CEFIslaDelTesoroContext _context;
        private ICategoriaTesoroServicio _categoriaTesoroServicio;
        
        public TesorosController(PW320231CEFIslaDelTesoroContext context,
            ICategoriaTesoroServicio categoriaTesoroServicio)
        {
            _context = context;
            _categoriaTesoroServicio = categoriaTesoroServicio;
        }
        public IActionResult Index()
        {
            var tesoros = _context.Tesoros.ToList();
            return View(tesoros);
        }

        public IActionResult Crear()
        {
            ViewBag.Ubicaciones = _context.Ubicacions
                   .OrderBy(o => o.Nombre)
                   .ToList();
            ViewBag.CategoriaTesoros = _categoriaTesoroServicio.ObtenerTodos();

            return View(new Tesoro());
        }

        [HttpPost]
        public IActionResult Crear(Tesoro tesoro, int[] IdCategoriaTesoros)
        {
            if (ModelState.IsValid)
            {
                tesoro.IdUbicacion = tesoro.IdUbicacion;
                tesoro.IdCategoriaTesoros = _categoriaTesoroServicio.ObtenerFiltrado(IdCategoriaTesoros);

                _context.Tesoros.Add(tesoro);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.Ubicaciones = _context.Ubicacions
                   .OrderBy(o => o.Nombre)
                   .ToList();
            ViewBag.CategoriaTesoros = _categoriaTesoroServicio.ObtenerTodos();

            return View(tesoro);
        }

        public IActionResult Editar(int id)
        {
            var tesoro = _context.Tesoros
                    .Include(t => t.IdCategoriaTesoros)
                    .FirstOrDefault(t => t.Id == id);


            if (tesoro != null)
            {
                ViewBag.Ubicaciones = _context.Ubicacions
                    .OrderBy(o => o.Nombre)
                    .ToList();
                ViewBag.CategoriaTesoros = _categoriaTesoroServicio.ObtenerTodos();

                return View(tesoro);
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult Editar2(Tesoro tesoro)
        {
            if (ModelState.IsValid)
            {
                _context.Tesoros.Update(tesoro);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(tesoro);
        }
        
        [HttpPost]
        public IActionResult Editar(Tesoro tesoro, int[] IdCategoriaTesoros)
        {
            //Actualizando manualmente cada campo (es mas seguro)
            if (ModelState.IsValid)
            {
                var tesoroEnBD = _context.Tesoros
                    .Include(t => t.IdCategoriaTesoros)
                    .FirstOrDefault(t=> t.Id == tesoro.Id);

                if (tesoroEnBD == null)
                {
                    return View(tesoro);
                }

                tesoroEnBD.Nombre = tesoro.Nombre;
                tesoroEnBD.Descripcion = tesoro.Descripcion;
                tesoroEnBD.ImagenUrl = tesoro.ImagenUrl;
                tesoroEnBD.Valor = tesoro.Valor;
                tesoroEnBD.IdUbicacion = tesoro.IdUbicacion;

                // Actualizar las categorías de tesoro
                tesoroEnBD.IdCategoriaTesoros.Clear();

                foreach (var idCategoriaTesoro in IdCategoriaTesoros)
                {
                    var categoriaTesoro = _context.CategoriaTesoros.Find(idCategoriaTesoro);
                    if (categoriaTesoro != null)
                    {
                        tesoroEnBD.IdCategoriaTesoros.Add(categoriaTesoro);
                    }
                }

                _context.Update(tesoroEnBD);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }
            
            ViewBag.Ubicaciones = _context.Ubicacions
                .OrderBy(o=> o.Nombre)
                .ToList();

            ViewBag.CategoriaTesoros = _categoriaTesoroServicio.ObtenerTodos();

            return View(tesoro);
        }

        public IActionResult Eliminar(int id)
        {
            var tesoro = _context.Tesoros.Find(id);
            if (tesoro != null)
            {
                _context.Tesoros.Remove(tesoro);
                _context.SaveChanges();
            }
            return RedirectToAction("Index");
        }
    }
}

Clase-7/Clase7.EF.IslaDelTesoro/Clase7.EF.IslaDelTesoro.Web/Controllers/UbicacionController.cs
using Clase7.EF.IslaDelTesoro.Data.Entidades;
using Microsoft.AspNetCore.Mvc;

namespace Clase7.EF.IslaDelTesoro.Web.Controllers
{
    public class UbicacionController : Controller
    {
        private PW320231CEFIslaDelTesoroContext _context;

        public UbicacionController(PW320231CEFIslaDelTesoroContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            var ubicaciones = _context.Ubicacions.ToList();
            return View(ubicaciones);
        }
       

        public IActionResult Crear()
        {
            var NuevaUbicacion = new Ubicacion();
            return View(NuevaUbicacion);
        }

        [HttpPost]
        public IActionResult Crear(Ubicacion nuevaUbicacion)
        {
            if (ModelState.IsValid)
            {
            _context.Add(nuevaUbicacion);
            _context.SaveChanges();
            return RedirectToAction("Index");
            }
            return View(nuevaUbicacion);
        }

        public IActionResult Editar(int id)
        {
            var ubicacionencontrada = _context.Ubicacions.Find(id);
            if (ubicacionencontrada != null)
            {
                return View(ubicacionencontrada);
            }
            return RedirectToAction("Index");
        }
        [HttpPost]
        public IActionResult Editar(Ubicacion ubicacionActualizada)
        {
            if (ModelState.IsValid)
            {
                var ubicacionAActualizar=_context.Ubicacions.Find(ubicacionActualizada.Id);
                if (ubicacionAActualizar != null) {
                    ubicacionAActualizar.Nombre = ubicacionActualizada.Nombre;
                    _context.SaveChanges(); 
                    return RedirectToAction("Index");
                }  
            }
            return View(ubicacionActualizada);
        }

        public IActionResult Eliminar(int id)
        {

            var ubicacionARemover = _context.Ubicacions.Find(id);
            if (ubicacionARemover != null)
            {
                _context.Remove(ubicacionARemover);
                _context.SaveChanges();
            }

            return RedirectToAction("Index");
        }
    }
}

Clase-7/Clase7.EF.IslaDelTesoro/Clase7.EF.IslaDelTesoro.Web/Views/CategoriasTesoros/Index.cshtml
@using Clase7.EF.IslaDelTesoro.Data.Entidades
@model List<CategoriaTesoro>

@{
    ViewData["Title"] = "Categorias Tesoro";
}
<table>
    <tr>
        <th>IdCategoriaTesoro</th>
        <th>Nombre</th>
        <th>Operacion</th>
    </tr>
    @foreach (CategoriaTesoro categoria in Model)
    {
        <tr>
            <td>@categoria.IdCategoriaTesoro</td>
            <td>@categoria.Nombre</td>
            <td><a href="/CategoriasTesoros/Eliminar/@categoria.IdCategoriaTesoro">@categoria.Nombre</a></td>
        </tr>
    }
</table>

Clase-7/Clase7.EF.IslaDelTesoro/Clase7.EF.IslaDelTesoro.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Clase7.EF.IslaDelTesoro.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Clase7.EF.IslaDelTesoro.Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Clase7.EF.IslaDelTesoro.Web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Tesoros" asp-action="Index">Tesoros</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Ubicacion" asp-action="Index">Ubicaciones</a>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="CategoriasTesoros" asp-action="Index">Categorias Tesoros</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Clase7.EF.IslaDelTesoro.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Clase-7/Clase7.EF.IslaDelTesoro/Clase7.EF.IslaDelTesoro.Web/Views/Ubicacion/Crear.cshtml
@model Clase7.EF.IslaDelTesoro.Data.Entidades.Ubicacion 
@{
    ViewData["Title"] = "Agregar Ubicacion";
}

<h1>Ingresar Nuevas Ubicaciones</h1>

<form action="/Ubicacion/Crear" method="post">

    <div>
        Nombre: <input type="text" name="Nombre" value="@Model.Nombre" />
    </div>
    <div>
        
    </div>

    <input type="submit" value="Crear" />
</form>

Clase-7/Clase7.EF.IslaDelTesoro/Clase7.EF.IslaDelTesoro.Web/Views/Ubicacion/Editar.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model Clase7.EF.IslaDelTesoro.Data.Entidades.Ubicacion
@{
    ViewData["Title"] = "Editar Ubicacion";
}

<h1>Editar Ubicaciones</h1>



<form action="/Ubicacion/Editar" method="post">
    <input type="hidden" value="@Model.Id" name="Id" />
    <div>
        Nombre: <input type="text" name="Nombre" value="@Model.Nombre" />
    </div>
    <input type="submit" value="Guardar" />
</form>

Clase-7/Clase7.EF.IslaDelTesoro/Clase7.EF.IslaDelTesoro.Web/Views/Ubicacion/Index.cshtml
@model IEnumerable<Clase7.EF.IslaDelTesoro.Data.Entidades.Ubicacion>

@{
    ViewData["Title"] = "Lista De ubicaciones";
}

<h1>Ubiacciones</h1>

<p>
    <a asp-action="Crear">Crear Una Nueva Ubicacion</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nombre)
            </th>
           
           
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                    @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td>
                    @Html.DisplayFor(modelItem => item.Nombre)
            </td>
            <td>
                <a asp-action="Editar" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Eliminar" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>